---
- name: Inclui variaveis para distribuicoes Linux
  include_vars: "{{ ansible_os_family }}.yml"
  tags: web    

- name: Instala Webserver Apache no Debian 9
  when: ansible_os_family == "Debian"
  apt:
    name: "{{packages_debian}}"
    state: installed
  notify:
    - Start Apache
  tags: web    

- name: Instala Webserver Apache no CentOS 7
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{packages_redhat}}"
    state: installed
  notify:
    - Start Httpd
  tags: web    

- name: Inicia e ativa na inicializacao o servico httpd
  when: ansible_os_family == "RedHat"
  systemd:
    name: httpd
    state: started
    enabled: yes
  tags: web    
