---
- name: Configura senha do usuario root
  mysql_user:
    name: root
    password: 4linux
    check_implicit_admin: true
  tags: banco    

- name: Cria banco de dados dexter500
  mysql_db:
    name: dexter500
    state: present
  tags: banco    

- name: Importar tabelas para o banco de dados
  shell: mysql dexter500 < /tmp/dump.sql
  tags: banco    

- name: Adiciona usuario admin e configura privilegios
  mysql_user:
    name: admin
    password: 4linux
    host: "{{item}}"
    state: present
    priv: "dexter500.*:ALL"
  with_items:
    - "localhost"
    - "127.0.0.1"
    - "%"
  tags: banco    
