#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com";

mod '<user_puppetforge>-confsbase'
#mod '<user_puppetforge>-memcached'
#mod '<user_puppetforge>-mysqlserver'

#mod 'puppet-webserver',
  #:git => 'https://github.com/<user_github>/puppet-webserver.git',
  #:branch => 'homolog'

#mod 'puppet-balancer',
  #:git => 'https://github.com/<user_github>/puppet-balancer.git',
  #:branch => 'production'
