---
- hosts: local
  tasks:
    - name: Adicionando a chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Adicionando o repositorio do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        state: present
        filename: 'docker'
      register: docker_repo_add

    - name: Atualizando a lista de pacotes
      when: docker_repo_add|success
      shell: apt update
